-- Add any missing columns to players table
ALTER TABLE players
ADD COLUMN IF NOT EXISTS first_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS country VARCHAR(50),
ADD COLUMN IF NOT EXISTS height INTEGER,
ADD COLUMN IF NOT EXISTS weight INTEGER,
ADD COLUMN IF NOT EXISTS birth_place VARCHAR(255),
ADD COLUMN IF NOT EXISTS residence VARCHAR(255),
ADD COLUMN IF NOT EXISTS college VARCHAR(255),
ADD COLUMN IF NOT EXISTS tour VARCHAR(100),
ADD COLUMN IF NOT EXISTS alias VARCHAR(255),
ADD COLUMN IF NOT EXISTS abbr_name VARCHAR(50),
ADD COLUMN IF NOT EXISTS handedness CHAR(1),
ADD COLUMN IF NOT EXISTS turned_pro INTEGER,
ADD COLUMN IF NOT EXISTS member BOOLEAN,
ADD COLUMN IF NOT EXISTS birthday DATE,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
